// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: balanceService.proto

package com.balanceService;

public interface containsBalanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsBalance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string balance = 1;</code>
   */
  java.lang.String getBalance();
  /**
   * <code>string balance = 1;</code>
   */
  com.google.protobuf.ByteString
      getBalanceBytes();
}
