// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dateTimeService.proto

package com.dateTimeService;

public interface containsDateTimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsDateTime)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dateTime = 1;</code>
   */
  java.lang.String getDateTime();
  /**
   * <code>string dateTime = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();
}
