// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dateTimeService.proto

package com.dateTimeService;

public final class dateTimeServiceImpl {
  private dateTimeServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsDateTime_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsDateTime_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025dateTimeService.proto\"$\n\020containsDateT" +
      "ime\022\020\n\010dateTime\030\001 \001(\t2H\n\017dateTimeService" +
      "\0225\n\013GetDateTime\022\021.containsDateTime\032\021.con" +
      "tainsDateTime\"\000B,\n\023com.dateTimeServiceB\023" +
      "dateTimeServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_containsDateTime_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containsDateTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsDateTime_descriptor,
        new java.lang.String[] { "DateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
