// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: locationService.proto

package com.locationService;

public interface containsLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
