// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2FactorAuth.proto

package com.factorAuthService;

public interface containAuthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containAuth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
