// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transactionService.proto

package com.transactionService;

public interface containsTransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsTransaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transaction = 1;</code>
   */
  java.lang.String getTransaction();
  /**
   * <code>string transaction = 1;</code>
   */
  com.google.protobuf.ByteString
      getTransactionBytes();
}
