// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transactionService.proto

package com.transactionService;

public final class transactionServiceImpl {
  private transactionServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsTransaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsTransaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030transactionService.proto\"*\n\023containsTr" +
      "ansaction\022\023\n\013transaction\030\001 \001(\t2V\n\022transa" +
      "ctionService\022@\n\016GetTransaction\022\024.contain" +
      "sTransaction\032\024.containsTransaction\"\0000\001B2" +
      "\n\026com.transactionServiceB\026transactionSer" +
      "viceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_containsTransaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containsTransaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsTransaction_descriptor,
        new java.lang.String[] { "Transaction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
