// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spendingLimitService.proto

package com.spendingLimitService;

public interface containsSpendingLimitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsSpendingLimit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transaction = 1;</code>
   */
  java.lang.String getTransaction();
  /**
   * <code>string transaction = 1;</code>
   */
  com.google.protobuf.ByteString
      getTransactionBytes();
}
