// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spendingLimitService.proto

package com.spendingLimitService;

public final class spendingLimitServiceServiceImpl {
  private spendingLimitServiceServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsSpendingLimit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsSpendingLimit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032spendingLimitService.proto\",\n\025contains" +
      "SpendingLimit\022\023\n\013transaction\030\001 \001(\t2^\n\024sp" +
      "endingLimitService\022F\n\020GetSpendingLimit\022\026" +
      ".containsSpendingLimit\032\026.containsSpendin" +
      "gLimit\"\000(\001B=\n\030com.spendingLimitServiceB\037" +
      "spendingLimitServiceServiceImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_containsSpendingLimit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containsSpendingLimit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsSpendingLimit_descriptor,
        new java.lang.String[] { "Transaction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
